# Generated by Django 3.2.6 on 2022-03-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('title', models.TextField(verbose_name='标题')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('excerpt', models.TextField(blank=True, null=True, verbose_name='引用')),
                ('category', models.CharField(blank=True, max_length=20, null=True, verbose_name='种类')),
                ('status', models.CharField(default='active', max_length=20, verbose_name='状态')),
                ('parent', models.BigIntegerField(default=-1, verbose_name='父节点')),
                ('comment_count', models.BigIntegerField(default=0, verbose_name='评论数')),
            ],
        ),
    ]
