# Generated by Django 3.2.6 on 2022-03-28 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('title', models.TextField(max_length=128, verbose_name='标题')),
                ('content', models.TextField(blank=True, max_length=1048576, verbose_name='内容')),
                ('excerpt', models.TextField(blank=True, max_length=2000, null=True, verbose_name='引用')),
                ('category', models.CharField(blank=True, max_length=20, null=True, verbose_name='种类')),
                ('status', models.CharField(default='active', max_length=20, verbose_name='状态')),
                ('parent', models.BigIntegerField(default=-1, verbose_name='父节点')),
                ('comment_count', models.BigIntegerField(default=0, verbose_name='评论数')),
                ('likes', models.IntegerField(default=0, verbose_name='点赞数')),
                ('author', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='post_set', to='users.userinfo', verbose_name='作者')),
            ],
        ),
    ]
