# Generated by Django 3.2.6 on 2022-03-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(max_length=128, unique=True, verbose_name='标题'),
        ),
    ]
