# Generated by Django 3.2.6 on 2022-03-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(default=None, max_length=11, null=True, verbose_name='手机号码'),
        ),
    ]
