# Generated by Django 3.2.6 on 2022-03-06 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usertitle_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertitle',
            name='owner',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='title_set', to='users.userinfo', verbose_name='用户头衔'),
        ),
    ]
