# Generated by Django 3.2.6 on 2022-03-23 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userinfo_phone'),
        ('users', '0004_alter_usertitle_owner'),
    ]

    operations = [
    ]
