# Generated by Django 3.2.6 on 2022-03-23 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_20220323_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertitle',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_set', to='users.userinfo', verbose_name='头衔拥有者'),
        ),
    ]
