# Generated by Django 3.2.6 on 2022-03-22 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_userinfo_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.BigIntegerField(verbose_name='帖子id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('content', models.TextField(verbose_name='内容')),
                ('approved', models.BigIntegerField(default=0, verbose_name='赞成')),
                ('category', models.CharField(max_length=20, null=True, verbose_name='种类')),
                ('author', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comment_set', to='users.userinfo', verbose_name='评论者')),
            ],
        ),
    ]
