# Generated by Django 3.2.6 on 2022-03-22 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_userinfo_phone'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavoriteFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='文件夹名字')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_folder_set', to='users.userinfo', verbose_name='所关联的用户')),
            ],
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_set', to='favorite.userfavoritefolder', verbose_name='所关联的文件夹')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='posts.post', verbose_name='所关联的文章')),
            ],
        ),
    ]
