# Generated by Django 3.2.6 on 2022-03-23 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('favorite', '0001_initial'),
        ('posts', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfavoritefolder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_folder_set', to='users.userinfo', verbose_name='所关联的用户'),
        ),
        migrations.AddField(
            model_name='userfavorite',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_set', to='favorite.userfavoritefolder', verbose_name='所关联的文件夹'),
        ),
        migrations.AddField(
            model_name='userfavorite',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_favorite', to='posts.post', verbose_name='收藏所关联的文章'),
        ),
    ]
