# Generated by Django 3.2.6 on 2022-03-23 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('favorite', '0002_userfavoritefolder_create_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfavoritefolder',
            name='name',
        ),
        migrations.AddField(
            model_name='userfavoritefolder',
            name='folder_name',
            field=models.CharField(max_length=20, null=True, verbose_name='收藏文件夹名字'),
        ),
        migrations.AlterField(
            model_name='userfavorite',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_post', to='posts.post', verbose_name='收藏所关联的文章'),
        ),
    ]
