# Generated by Django 3.2.6 on 2022-03-31 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('cate_name', models.CharField(max_length=64, null=True, unique=True, verbose_name='类别')),
                ('level', models.IntegerField(blank=True, null=True, verbose_name='层级')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='subjects.subject', verbose_name='父类别')),
            ],
            options={
                'verbose_name': '学科',
                'db_table': 'Subject',
            },
        ),
    ]
