# Generated by Django 3.2.6 on 2022-03-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='level',
            field=models.IntegerField(null=True, verbose_name='层级'),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject',
            field=models.CharField(max_length=255, null=True, verbose_name='学科名'),
        ),
    ]
