# Generated by Django 3.2.6 on 2022-03-31 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_auto_20220331_1535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': '学科'},
        ),
        migrations.AlterField(
            model_name='subject',
            name='cate_name',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='level',
            field=models.IntegerField(blank=True, null=True, verbose_name='层级'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='subjects.subject', verbose_name='父类别'),
        ),
    ]
