# Generated by Django 3.2.6 on 2022-03-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_auto_20220318_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='学科名'),
        ),
    ]
