# Generated by Django 3.2.6 on 2022-03-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_auto_20220318_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectCategory_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, null=True, unique=True, verbose_name='一级学科名')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectCategory_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, null=True, unique=True, verbose_name='二级学科名')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectCategory_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, null=True, unique=True, verbose_name='三级学科名')),
            ],
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
